### ISSUE TITLE
About robotframework-drupallibrary

### ISSUE THREAD

**Issue by glenfant** [alterway/contrib.alterway.fr#3]
Ce composant n'est pas une "intégration de RobotFramework dans Drupal" mais un "Jeu de keywords  RobotFramework pour tester des sites Drupal".

**Comment by Halleck45** [comment]
Il ne reste plus qu'à faire une petite PR ;)

**Comment by glenfant** [comment]
Ci fait..

**Comment by Halleck45** [comment]
Impec :)
